Arquisoft/lomap_en2b

README.md

Added my name to the team member list

Added Diego to list

---

docs/06_runtime_view.adoc

Part 6 of the documentation, related to Runtime View.
[Link to compile the UML sequence diagrams online](http://www.plantuml.com/plantuml/uml/)

Doc section6 diego

---

docs/08_concepts.adoc

[Link with the PlantUml with the model](http://www.plantuml.com/plantuml/uml/TPB1JiCm38RlVOgSaVO2Ew19xCA92GGNn26DJMTeuyfnLw69TyTgkqMXMa_D5_lF_rlU9VMYGzTMN7zXKFUQKCwLis_4-X7SrhseK6mc9DnYIIYzeT0d8HYlsUvzh7whYzf168QWis1WmA8v-gu4W2a8zKeS2zuB1Qi47keM9vAKm_VMKTJPHkURKYfunORbfu0ZKdFKgr3s-II0idQPvr0G3o2OKcbnJcfmoVp-CKVoQd9xhulleLPMtnxMYOxKzwQslhdH81YGJWZx_48Ez8mdml6y2b2OVVWVLRpQRnvhuAx3gDSQqvycvUusc_jfLPOps_aIl9hVjferotqxZ61hzmS0)

Documentation part 8 - Concepts

---

docs/09_design_decisions.adoc

Docu seccion9

---

docs/10_quality_scenarios.adoc

Edit: [Link to the UML](https://www.plantuml.com/plantuml/png/TL712eCm3BttAthKWxym76F7WMFi0xeQ8Q1rIzE1Vpzh40t3GqlwtYDzBwaZE-8qzCOKz-HwvCaIV18I310ubjOKbx65qXJFcEzhrw5727wQ7mtXrotLkNLlTY_C3HRjLjyS1fxFXZGZxRGFy8aWz_0U8gxuaP-gEbcnTAGGIRPhnRK0og8YvDz_Gk9fR4scKPL8t0cXmsjoFqk5hnCnDOHstiqF)

Added the point 10 of the documentation

---

docs/12_glossary.adoc

2 terms added to the glossary.

Added N-Tier architecture and MVC to the glossary

---

docs/01_introduction_and_goals.adoc

Following the teacher's advice I decided to add HappySw to the list of Stakeholders, also I rewrote the Council Of Brussels expectations.

Added HappySw to the list of Stakeholders

---

docs/02_architecture_constraints.adoc
docs/04_solution_strategy.adoc
docs/09_design_decisions.adoc

I've tried to correct some of the possible mistakes I had made during the first deliverable.

Correction of mistakes Docs0.1

---

webapp/src/pages/login/Login.tsx
webapp/src/pages/login/login.css
webapp/src/pages/profile/Profile.tsx

A simple addition of a css file to the login to make it more presentable (has to be improved but it is better than default). Should not give problems for merging.

Solid improvements

---

docs/04_solution_strategy.adoc
docs/09_design_decisions.adoc

Some changes made on 2 points of the documentation

Pedro documentation1.0

---

restapi/controllers/landmarks.ts
restapi/controllers/solid.ts
restapi/package-lock.json
restapi/package.json
restapi/solid/solidLandmark.ts
webapp/package-lock.json
webapp/src/shared/shareddtypes.ts

Main code to allow us to add locations in solid

Pedro adding locations to solid

---

webapp/src/pages/friends/Friends.tsx

Creating some ui to see our friends

Edited friends page

---

webapp/src/components/navbar/Navbar.tsx
webapp/src/components/navbar/navbar.css

Updated the login button so that it now actually works. It also changes to a logout button if the session is active.

Updated the login button

---

docs/02_architecture_constraints.adoc
docs/04_solution_strategy.adoc
docs/05_building_block_view.adoc
docs/07_deployment_view.adoc
docs/09_design_decisions.adoc
docs/12_glossary.adoc

Updated some points of the documentation that were really behind, and added a design decision.

Documentation update.

---

webapp/src/pages/addLandmark/AddLandmark.tsx

Earlier today I was told by @plg22 that the page did not work properly. This minor fix solves that problem.

Minor fix to the add landmark page

---

docs/09_design_decisions.adoc
webapp/e2e/features/add-landmarks.feature
webapp/e2e/features/see-landmarks.feature
webapp/e2e/steps/add-landmark.steps.ts
webapp/e2e/steps/find-friends.steps.ts
webapp/e2e/steps/profile.steps.ts
webapp/e2e/steps/see-landmarks.steps.ts

I've tried getting closer to the final version of the e2e tests, although the way to login is not decided or written yet. Furthermore I've also added a pair of design decisions to the documentation

More e2e tests and design decisions

---

webapp/src/pages/addLandmark/AddLandmark.tsx
webapp/src/pages/addLandmark/solidLandmarkManagement.tsx
webapp/src/pages/home/Home.tsx
webapp/src/pages/otherUsersLandmark/LandmarkFriend.tsx

* Added landmark to the following pages:
* /landmark/add
* /landmark/filter
* Improved the UI of the landmark/filter page upon the base that already existed. Currently for friend retrieval to be incorporated to improve it further.

Improved the UI and added landmark retrieval to it

---

webapp/src/App.tsx
webapp/src/components/leftBar/LeftBar.tsx
webapp/src/components/navbar/Navbar.tsx
webapp/src/pages/friends/Friends.tsx
webapp/src/pages/home/Home.tsx
webapp/src/pages/login/Login.tsx
webapp/src/pages/users/Users.tsx

Added the login page as the default "/" page, also now all the subpages have the "/main" before written

Login fixed

---

webapp/src/pages/addLandmark/solidLandmarkManagement.tsx

Backend implemented for that (in the webapp)

Reading from friends and adding them in SOLID.

---

webapp/src/pages/addLandmark/solidLandmarkManagement.tsx
webapp/src/shared/shareddtypes.ts

Added functionality to support reviews and scores in the backend, missing the frontend.

Landmarks reviews and scores 

---

webapp/src/pages/addLandmark/AddLandmark.tsx
webapp/src/pages/addLandmark/addLandmark.css
webapp/src/pages/addLandmark/solidLandmarkManagement.tsx
webapp/src/shared/shareddtypes.ts

Now images and a description can be added when creating a landmark

Front improvement

---

webapp/src/pages/addLandmark/solidLandmarkManagement.tsx
webapp/src/pages/home/Home.tsx
webapp/src/pages/otherUsersLandmark/LandmarkFriend.tsx
webapp/src/shared/shareddtypes.ts

Added the page to filter and review landmarks

Added the page to filter and review landmarks

---

webapp/src/pages/addLandmark/solidLandmarkManagement.tsx

solidLandmarkManagement

---

webapp/e2e/features/find-friends.feature
webapp/e2e/features/friends-list.feature
webapp/e2e/features/profile.feature
webapp/e2e/features/see-landmarks.feature
webapp/e2e/jest.config.ts
webapp/e2e/steps/add-landmark.steps.ts
webapp/e2e/steps/find-friends.steps.ts
webapp/e2e/steps/friends-list.steps.ts
webapp/e2e/steps/profile.steps.ts
webapp/e2e/steps/see-landmarks.steps.ts
webapp/package-lock.json
webapp/package.json

We have the right orders, but the main page does not load

The closest to running e2e

---

webapp/src/pages/addLandmark/AddLandmark.tsx
webapp/src/pages/otherUsersLandmark/LandmarkFriend.tsx
webapp/src/solidHelper/solidLandmarkManagement.tsx

POD when storing the landmarks

Show info about landmarks simple, also fix on the location inside the

---

webapp/src/pages/profile/Profile.tsx

Axios_error on webApp test solved

---

webapp/src/pages/addLandmark/AddLandmark.tsx

Little error fix
